<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Support\SetMeasure;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach (self::library() as $group => $names) {
            foreach ($names as $name) {
                $exercise = Exercise::query()->firstOrNew([
                    'user_id' => null,
                    'name' => $name,
                ]);
                $exercise->group = $group;
                $exercise->measure = SetMeasure::forExerciseName($name);
                $exercise->session_types = self::typesFor($name, $group);

                if ($exercise->approved_at === null) {
                    $exercise->approved_at = now();
                }

                $exercise->save();
            }
        }
    }

    /**
     * @return array<string, list<string>>
     */
    public static function library(): array
    {
        return [
            'Lower Body' => [
                'Barbell Back Squat',
                'Front Squat',
                'Goblet Squat',
                'Bulgarian Split Squat',
                'Walking Lunge',
                'Step-Up',
                'Romanian Deadlift',
                'Conventional Deadlift',
                'Hip Thrust',
                'Leg Press',
                'Leg Extension',
                'Leg Curl',
                'Standing Calf Raise',
                'Air Squat',
                'Banded Hip March',
                'Barbell Hack Squat',
                'Barbell Lunge',
                'Barbell Walking Lunge',
                'Belt Squat',
                'Body Weight Lunge',
                'Bodyweight Leg Curl',
                'Box Jump',
                'Box Squat',
                'Cable Machine Hip Adduction',
                'Chair Squat',
                'Curtsy Lunge',
                'Depth Jump',
                'Dumbbell Lunge',
                'Dumbbell Walking Lunge',
                'Dumbbell Squat',
                'Glute Ham Raise',
                'Hack Squat Machine',
                'Half Air Squat',
                'Heel Walk',
                'Hip Adduction Against Band',
                'Hip Adduction Machine',
                'Jump Squat',
                'Jumping Lunge',
                'Kettlebell Front Squat',
                'Kettlebell Tibialis Raise',
                'Landmine Hack Squat',
                'Landmine Squat',
                'Lateral Bound',
                'Leg Curl On Ball',
                'Lying Leg Curl',
                'Nordic Hamstring Eccentric',
                'One-Legged Leg Extension',
                'One-Legged Lying Leg Curl',
                'One-Legged Seated Leg Curl',
                'Pause Squat',
                'Pendulum Squat',
                'Pin Squat',
                'Pistol Squat',
                'Poliquin Step-Up',
                'Prisoner Get Up',
                'Reverse Barbell Lunge',
                'Reverse Body Weight Lunge',
                'Reverse Dumbbell Lunge',
                'Reverse Nordic',
                'Safety Bar Squat',
                'Seated Leg Curl',
                'Shallow Body Weight Lunge',
                'Side Lunges (Bodyweight)',
                'Sled Push',
                'Smith Machine Bulgarian Split Squat',
                'Smith Machine Front Squat',
                'Smith Machine Lunge',
                'Smith Machine Romanian Deadlift',
                'Smith Machine Squat',
                'Sumo Squat',
                'Standing Cable Leg Extension',
                'Standing Hip Flexor Raise',
                'Standing Leg Curl',
                'Tibialis Band Pull',
                'Tibialis Raise',
                'Vertical Leg Press',
                'Zercher Squat',
                'Zombie Squat',
                'Back Extension',
                'Deficit Deadlift',
                'Dumbbell Deadlift',
                'Fat Bar Deadlift',
                'Floor Back Extension',
                'Good Morning',
                'Pause Deadlift',
                'Rack Pull',
                'Single Leg Deadlift with Kettlebell',
                'Smith Machine Deadlift',
                'Snatch Grip Deadlift',
                'Stiff-Legged Deadlift',
                'Sumo Deadlift',
                'Superman Raise',
                'Trap Bar Deadlift With High Handles',
                'Trap Bar Deadlift With Low Handles',
                'Banded Side Kicks',
                'Cable Glute Kickback',
                'Cable Pull Through',
                'Cable Machine Hip Abduction',
                'Clamshells',
                'Cossack Squat',
                'Death March with Dumbbells',
                'Donkey Kicks',
                'Dumbbell Romanian Deadlift',
                'Dumbbell Frog Pumps',
                'Fire Hydrants',
                'Frog Pumps',
                'Glute Bridge',
                'Hip Abduction Against Band',
                'Hip Abduction Machine',
                'Hip Thrust Machine',
                'Hip Thrust With Band Around Knees',
                'Lateral Walk With Band',
                'Machine Glute Kickbacks',
                'One-Legged Glute Bridge',
                'One-Legged Hip Thrust',
                'Reverse Hyperextension',
                'Smith Machine Hip Thrust',
                'Single Leg Romanian Deadlift',
                'Standing Hip Abduction Against Band',
                'Standing Glute Kickback in Machine',
                'Standing Glute Push Down',
                'Barbell Standing Calf Raise',
                'Barbell Seated Calf Raise',
                'Calf Raise in Leg Press',
                'Donkey Calf Raise',
                'Eccentric Heel Drop',
                'Heel Raise',
                'Seated Calf Raise',
            ],
            'Upper Body' => [
                'Bench Press',
                'Incline Bench Press',
                'Overhead Press',
                'Dumbbell Shoulder Press',
                'Pull-Up',
                'Chin-Up',
                'Lat Pulldown',
                'Barbell Row',
                'Dumbbell Row',
                'Seated Cable Row',
                'Push-Up',
                'Dip',
                'Bicep Curl',
                'Hammer Curl',
                'Tricep Pushdown',
                'Lateral Raise',
                'Face Pull',
                'Assisted Dip',
                'Band-Assisted Bench Press',
                'Bench Press Against Band',
                'Board Press',
                'Cable Chest Press',
                'Clap Push-Up',
                'Close-Grip Bench Press',
                'Close-Grip Feet-Up Bench Press',
                'Cobra Push-Up',
                'Decline Bench Press',
                'Decline Push-Up',
                'Dumbbell Chest Fly',
                'Dumbbell Chest Press',
                'Dumbbell Decline Chest Press',
                'Dumbbell Floor Press',
                'Dumbbell Pullover',
                'Feet-Up Bench Press',
                'Floor Press',
                'Incline Dumbbell Press',
                'Incline Push-Up',
                'Kettlebell Floor Press',
                'Kneeling Incline Push-Up',
                'Kneeling Push-Up',
                'Machine Chest Fly',
                'Machine Chest Press',
                'Medicine Ball Chest Pass',
                'Pec Deck',
                'Pin Bench Press',
                'Plank to Push-Up',
                'Push-Up Against Wall',
                'Push-Up With Feet in Rings',
                'Resistance Band Chest Fly',
                'Ring Dip',
                'Seated Cable Chest Fly',
                'Smith Machine Bench Press',
                'Smith Machine Incline Bench Press',
                'Smith Machine Reverse Grip Bench Press',
                'Standing Cable Chest Fly',
                'Standing Resistance Band Chest Fly',
                'Arnold Press',
                'Band External Shoulder Rotation',
                'Band Internal Shoulder Rotation',
                'Band Pull-Apart',
                'Banded Face Pull',
                'Barbell Front Raise',
                'Barbell Rear Delt Row',
                'Barbell Upright Row',
                'Behind the Neck Press',
                'Cable Internal Shoulder Rotation',
                'Cable External Shoulder Rotation',
                'Cable Front Raise',
                'Cable Lateral Raise',
                'Cable Rear Delt Row',
                'Cuban Press',
                'Dumbbell Front Raise',
                'Dumbbell Horizontal Internal Shoulder Rotation',
                'Dumbbell Horizontal External Shoulder Rotation',
                'Dumbbell Rear Delt Row',
                'Front Hold',
                'Handstand Push-Up',
                'Kettlebell Halo',
                'Kettlebell Press',
                'Kettlebell Push Press',
                'Landmine Press',
                'Lying Dumbbell External Shoulder Rotation',
                'Lying Dumbbell Internal Shoulder Rotation',
                'Machine Lateral Raise',
                'Machine Shoulder Press',
                'Monkey Row',
                'One-Arm Landmine Press',
                'Plate Front Raise',
                'Poliquin Raise',
                'Push Press',
                'Resistance Band Lateral Raise',
                'Reverse Cable Flyes',
                'Reverse Dumbbell Flyes',
                'Reverse Dumbbell Flyes on Incline Bench',
                'Reverse Machine Fly',
                'Seated Dumbbell Shoulder Press',
                'Seated Barbell Overhead Press',
                'Seated Kettlebell Press',
                'Seated Smith Machine Shoulder Press',
                'Smith Machine Landmine Press',
                'Snatch Grip Behind the Neck Press',
                'Wall Walk',
                'Z Press',
                'Barbell Curl',
                'Barbell Preacher Curl',
                'Bayesian Curl',
                'Bodyweight Curl',
                'Cable Crossover Bicep Curl',
                'Cable Curl With Bar',
                'Cable Curl With Rope',
                'Concentration Curl',
                'Drag Curl',
                'Dumbbell Curl',
                'Dumbbell Preacher Curl',
                'EZ Curl',
                'Incline Dumbbell Curl',
                'Kettlebell Curl',
                'Lying Bicep Cable Curl on Bench',
                'Lying Bicep Cable Curl on Floor',
                'Machine Bicep Curl',
                'Overhead Cable Curl',
                'Reverse Barbell Curl',
                'Reverse Dumbbell Curl',
                'Resistance Band Curl',
                'Spider Curl',
                'Zottman Curl',
                'Barbell Standing Triceps Extension',
                'Barbell Incline Triceps Extension',
                'Barbell Lying Triceps Extension',
                'Bench Dip',
                'Crossbody Cable Triceps Extension',
                'Close-Grip Push-Up',
                'Dumbbell Lying Triceps Extension',
                'Dumbbell Standing Triceps Extension',
                'EZ Bar Lying Triceps Extension',
                'Machine Overhead Triceps Extension',
                'Overhead Cable Triceps Extension (Lower Position)',
                'Overhead Cable Triceps Extension (Upper Position)',
                'Smith Machine Skull Crushers',
                'Tate Press',
                'Tricep Bodyweight Extension',
                'Tricep Pushdown With Bar',
                'Tricep Pushdown With Rope',
                'Assisted Chin-Up',
                'Assisted Pull-Up',
                'Banded Muscle-Up',
                'Barbell Shrug',
                'Cable Close Grip Seated Row',
                'Cable Wide Grip Seated Row',
                'Chest-Supported Dumbbell Row',
                'Chest to Bar',
                'Close-Grip Chin-Up',
                'Close-Grip Lat Pulldown',
                'Dumbbell Shrug',
                'Gorilla Row',
                'Inverted Row',
                'Inverted Row with Underhand Grip',
                'Jumping Muscle-Up',
                'Kettlebell Row',
                'Kroc Row',
                'Lat Pulldown With Neutral Grip',
                'Lat Pulldown With Pronated Grip',
                'Lat Pulldown With Supinated Grip',
                'Muscle-Up (Bar)',
                'Muscle-Up (Rings)',
                'Neutral Close-Grip Lat Pulldown',
                'One-Handed Cable Row',
                'One-Handed Lat Pulldown',
                'Pendlay Row',
                'Pull-Up With a Neutral Grip',
                'Renegade Row',
                'Rope Pulldown',
                'Ring Pull-Up',
                'Ring Row',
                'Scap Pull-Up',
                'Seal Row',
                'Seated Machine Row',
                'Smith Machine One-Handed Row',
                'Straight Arm Lat Pulldown',
                'T-Bar Row',
                'Towel Pull-Up',
                'Towel Row',
                'Barbell Wrist Curl',
                'Barbell Wrist Curl Behind the Back',
                'Bar Hang',
                'Dumbbell Wrist Curl',
                'Gripper',
                'One-Handed Bar Hang',
                'Plate Pinch',
                'Plate Wrist Curl',
                'Wrist Roller',
                'Barbell Wrist Extension',
                'Dumbbell Wrist Extension',
                'Lying Neck Curl',
                'Lying Neck Extension',
                'Prone Neck Bridge',
                'Supine Neck Bridge',
            ],
            'Core' => [
                'Plank',
                'Dead Bug',
                'Hanging Leg Raise',
                'Cable Crunch',
                'Ab Wheel Rollout',
                'Russian Twist',
                'Ball Slams',
                'Bicycle Crunch',
                "Captain's Chair Knee Raise",
                "Captain's Chair Leg Raise",
                'Copenhagen Plank',
                'Core Twist',
                'Crunch',
                'Dead Bug With Dumbbells',
                'Dragon Flag',
                'Dumbbell Side Bend',
                'Dynamic Side Plank',
                'Hanging Knee Raise',
                'Hanging Sit-Up',
                'Hanging Windshield Wiper',
                'High to Low Wood Chop with Band',
                'High to Low Wood Chop with Cable',
                'Hollow Body Crunch',
                'Hollow Hold',
                'Horizontal Wood Chop with Band',
                'Horizontal Wood Chop with Cable',
                'Jackknife Sit-Up',
                'Kettlebell Plank Pull Through',
                'Kneeling Plank',
                'Kneeling Side Plank',
                'Landmine Rotation',
                'L-Sit',
                'Low to High Wood Chop with Band',
                'Low to High Wood Chop with Cable',
                'Lying Leg Raise',
                'Lying Windshield Wiper',
                'Lying Windshield Wiper with Bent Knees',
                'Machine Crunch',
                'Mountain Climbers',
                'Oblique Crunch',
                'Oblique Sit-Up',
                'Pallof Press',
                'Plank with Leg Lifts',
                'Plank with Shoulder Taps',
                'Side Plank',
                'Sit-Up',
                'Weighted Plank',
            ],
            'Cardio' => [
                'Outdoor Run',
                'Treadmill Run',
                'Rowing',
                'Cycling',
                'Jump Rope',
                'Burpee',
            ],
            'Full Body' => [
                'Clean and Press',
                'Kettlebell Swing',
                'Thruster',
                'Farmer Carry',
                'Devils Press',
                'Jerk',
                'Power Jerk',
                'Squat Jerk',
                'Split Jerk',
                'Turkish Get-Up',
                'Ground to Overhead',
                'Kettlebell Thrusters',
                'Block Clean',
                'Block Snatch',
                'Clean',
                'Clean and Jerk',
                'Hang Clean',
                'Hang Power Clean',
                'Hang Power Snatch',
                'Hang Snatch',
                'Kettlebell Clean',
                'Kettlebell Clean and Jerk',
                'Kettlebell Clean and Press',
                'Kettlebell Snatch',
                'Kettlebell Windmill',
                'One-Handed Kettlebell Swing',
                'Power Clean',
                'Power Snatch',
                'Snatch',
            ],
            'Mobility' => [
                'Cat-Cow',
                "World's Greatest Stretch",
                '90/90 Hip Switch',
                'Couch Stretch',
                'Pigeon Pose',
                'Downward Dog',
                'Thoracic Open Book',
                'Shoulder Pass-Through',
                'Jefferson Curl',
            ],
        ];
    }

    /**
     * Exercises that belong to a session type.
     *
     * Strength uses the body-part groups instead, so it is not listed here.
     *
     * @return array<string, list<string>>
     */
    public static function sessions(): array
    {
        return [
            'Cardio' => [
                'Rowing',
                'Cycling',
                'Jump Rope',
                'Burpee',
            ],
            'Bodyweight' => [
                'Bulgarian Split Squat',
                'Walking Lunge',
                'Step-Up',
                'Pull-Up',
                'Chin-Up',
                'Push-Up',
                'Dip',
                'Plank',
                'Dead Bug',
                'Hanging Leg Raise',
                'Russian Twist',
                'Burpee',
                'Clap Push-Up',
                'Cobra Push-Up',
                'Decline Push-Up',
                'Incline Push-Up',
                'Kneeling Incline Push-Up',
                'Kneeling Push-Up',
                'Plank to Push-Up',
                'Push-Up Against Wall',
                'Push-Up With Feet in Rings',
                'Ring Dip',
                'Handstand Push-Up',
                'Wall Walk',
                'Front Hold',
                'Bodyweight Curl',
                'Bench Dip',
                'Close-Grip Push-Up',
                'Tricep Bodyweight Extension',
                'Air Squat',
                'Body Weight Lunge',
                'Bodyweight Leg Curl',
                'Box Jump',
                'Chair Squat',
                'Curtsy Lunge',
                'Depth Jump',
                'Half Air Squat',
                'Heel Walk',
                'Jump Squat',
                'Jumping Lunge',
                'Lateral Bound',
                'Pistol Squat',
                'Prisoner Get Up',
                'Reverse Body Weight Lunge',
                'Shallow Body Weight Lunge',
                'Side Lunges (Bodyweight)',
                'Back Extension',
                'Banded Muscle-Up',
                'Chest to Bar',
                'Close-Grip Chin-Up',
                'Floor Back Extension',
                'Inverted Row',
                'Inverted Row with Underhand Grip',
                'Jumping Muscle-Up',
                'Muscle-Up (Bar)',
                'Muscle-Up (Rings)',
                'Pull-Up With a Neutral Grip',
                'Ring Pull-Up',
                'Ring Row',
                'Scap Pull-Up',
                'Superman Raise',
                'Clamshells',
                'Donkey Kicks',
                'Fire Hydrants',
                'Frog Pumps',
                'Glute Bridge',
                'One-Legged Glute Bridge',
                'Bicycle Crunch',
                'Copenhagen Plank',
                'Core Twist',
                'Crunch',
                'Dragon Flag',
                'Dynamic Side Plank',
                'Hanging Knee Raise',
                'Hanging Sit-Up',
                'Hanging Windshield Wiper',
                'Hollow Body Crunch',
                'Hollow Hold',
                'Jackknife Sit-Up',
                'Kneeling Plank',
                'Kneeling Side Plank',
                'L-Sit',
                'Lying Leg Raise',
                'Lying Windshield Wiper',
                'Lying Windshield Wiper with Bent Knees',
                'Mountain Climbers',
                'Oblique Crunch',
                'Oblique Sit-Up',
                'Plank with Leg Lifts',
                'Plank with Shoulder Taps',
                'Side Plank',
                'Sit-Up',
                'Donkey Calf Raise',
                'Eccentric Heel Drop',
                'Heel Raise',
                'Bar Hang',
                'One-Handed Bar Hang',
                'Towel Pull-Up',
                'Prone Neck Bridge',
                'Supine Neck Bridge',
            ],
            'Conditioning' => [
                'Rowing',
                'Cycling',
                'Jump Rope',
                'Burpee',
                'Kettlebell Swing',
                'Thruster',
                'Farmer Carry',
                'Clean and Press',
                'Walking Lunge',
                'Step-Up',
                'Box Jump',
                'Depth Jump',
                'Jump Squat',
                'Jumping Lunge',
                'Lateral Bound',
                'Devils Press',
                'Ball Slams',
                'Mountain Climbers',
                'One-Handed Kettlebell Swing',
                'Kettlebell Thrusters',
                'Medicine Ball Chest Pass',
            ],
            'Mobility' => self::library()['Mobility'],
        ];
    }

    /**
     * @return list<string>
     */
    public static function typesFor(string $name, ?string $group): array
    {
        $types = [];

        foreach (self::sessions() as $type => $names) {
            if (in_array($name, $names, true)) {
                $types[] = $type;
            }
        }

        foreach (match ($group) {
            'Upper Body' => ['Strength - Upper Body', 'Strength - Full Body'],
            'Lower Body' => ['Strength - Lower Body', 'Strength - Full Body'],
            'Core' => ['Strength - Upper Body', 'Strength - Lower Body', 'Strength - Full Body'],
            'Full Body' => ['Strength - Full Body'],
            default => [],
        } as $type) {
            $types[] = $type;
        }

        return array_values(array_unique($types));
    }
}
